$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: fatigue-endpoint-amy
model: azureml:fatigue:3

# This is the shorthand that replaces your whole "# 2" block
environment: azureml:fatigue-final-env:1

data_collector:
  sampling_rate: 1.0
  collections:
    request:
      enabled: "true"
    response:
      enabled: "true"

instance_type: Standard_DS2_v2
instance_count: 1
